export const recipeConstants = {
  SET_RECIPES: "SET_RECIPES",
  SET_SHOW_ADD_RECIPE_MODAL: "SET_SHOW_ADD_RECIPE_MODAL",
  ADD_RECIPE: "ADD_RECIPE",
  SET_SEARCH_FILTER: "SET_SEARCH_FILTER",
  SET_RADIO_FILTER: "SET_RADIO_FILTER",
  DELETE_RECIPE: "DELETE_RECIPE",
  EDIT_RECIPE: "EDIT_RECIPE",
  UPDATE_RECIPE: "UPDATE_RECIPE",
};
